### ISSUE TITLE
cli: output formats: support yaml

### ISSUE THREAD

**Issue by gfelbing** [stackitcloud/stackit-cli#120]
Most similar CLIs (kubectl, gcloud, openstack) support yaml in addition to pretty and json as an output format.
For me as user, this provides a perfect compromise between human-readability and fine granulated content of the response.
Output can be same as json content-wise, but rendered as yaml.

**Comment by GokceGK** [comment]
Hi @gfelbing ,

with the latest STACKIT CLI release [v0.6.0](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.6.0), YAML is supported as output format.
