### ISSUE TITLE
Allow specifying custom pager

### ISSUE THREAD

**Issue by Kumm-Kai** [stackitcloud/stackit-cli#154]
Currently, the `less` pager is assumed to exist in the users `PATH`. The STACKIT CLI should allow users to specify their preferred pager using the `PAGER` environment variable.

Additionally, the STACKIT CLI should fall back to not paging at all, if the `less` command is not found in the user's environment.

**Comment by GokceGK** [comment]
Hi @Kumm-Kai, 

with the latest STACKIT CLI release [v0.6.0](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.6.0), it is now possible to specify a custom pager.
