### ISSUE TITLE
🐛 stackit ske options --kubernetes-versions -o json returns all options

### ISSUE THREAD

**Issue by robinschneider** [stackitcloud/stackit-cli#246]
cli command `stackit ske options --kubernetes-versions -o json` returns all values not only kubernetes versions.
This is also the case for the other options like `volume-types`

This does not happen when using `-o pretty`

**Comment by joaopalet** [comment]
Hi @robinschneider,
Thanks for reporting, usually for the `JSON` output we return the raw full API response. In this case it's a single endpoint that provides all that information, so we will have a look and filter out the non-relevant information

**Comment by vicentepinto98** [comment]
This was fixed in the latest release [v0.7.0](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.7.0).
