### ISSUE TITLE
Release notes are missing changes that were included in a prerelease

### ISSUE THREAD

**Issue by Kumm-Kai** [stackitcloud/stackit-cli#255]
The generated release notes (e.g., [`v0.3.0`](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.3.0)) are not including all changes between the last non-prerelease version and the new version. Only the changes since the last release (regardless if it was a prerelease or not) are included.

**Comment by joaopalet** [comment]
Hi @Kumm-Kai,

Thanks for reporting!

I've fixed it for the [v0.3.0](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.3.0) release in question and changed the release notes generator implementation used by GoReleaser. I've created two test prereleases and it seems both are picking up the commits from the latest release (excluding prereleases). Will close the issue if it's working as expected after the next normal release also.

**Comment by joaopalet** [comment]
We have just released version [v0.4.0](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.4.0) and confirmed the release notes contain the full changelog from the last non-pre-release version.

Thanks again for noticing and reporting!
