### ISSUE TITLE
Debug printer interprets HTML encoding as printf format strings

### ISSUE THREAD

**Issue by j-b-e** [stackitcloud/stackit-cli#529]
Somewhere in the debug printer, strings containing HTML encoding (such as the HTML encoding of `User.Name@stackit.cloud` -> `User.name%40stackit.cloud`) are interpreted literally as printf format values.

This leads to DBG output lines like this
`DBG request to https://resource-manager.api.stackit.cloud/v2/projects?limit=50&member=User.Name%!s(MISSING)tackit.cloud&offset=0: GET HTTP/1.1`

**Comment by Fyusel** [comment]
Hi @j-b-e,

thank you for reporting this issue. It has been fixed in the release [v0.19.0](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.19.0).

If the problem persists, feel free to reopen this issue.
