### ISSUE TITLE
🐛 `service-account token create` cannot return json

### ISSUE THREAD

**Issue by robinschneider** [stackitcloud/stackit-cli#82]
Hello,

when i list tokens via cli it is possible to list them pretty or as json.
When I create a token, it does not return them as json, only pretty seems to work for me:
`stackit service-account token create --email "MAIL@sa.stackit.cloud" --output-format="json" --project-id="PROJECT_ID" -y`

**Comment by vicentepinto98** [comment]
Hi @robinschneider,
Thanks for opening the issue!

Some of the commands don't support the json output currently. 
We have it in our backlog to support json for more commands and we will work on it soon.

**Comment by robinschneider** [comment]
Alright, thank you.
I will use the curl function till it is implemented.

**Comment by GokceGK** [comment]
Hi @robinschneider ,

with the latest STACKIT CLI release [v0.2.3](https://github.com/stackitcloud/stackit-cli/releases/tag/v0.2.3), it is now possible to return the output in the JSON format for the service-account token creation.
