### ISSUE TITLE
Listing the parent project Id list more projects that is needed

### ISSUE THREAD

**Issue by pmanent** [stackitcloud/stackit-cli#84]
Hello @stackit-cli,

After installation and authentication I'm able to list a bunch of projects that I don't have access to.(More than 2500 projects)

The list of the projects command I executes is like this: 
`stackit project list --parent-id XXXXXXXX-XXXXXXXXX-XXXXXX-XXXXX`

I was expecting only to see my projects, not other projects.

We should see our projects in the project list command, right?

Regards,

Pere Manent.

**Comment by hcsa73** [comment]
Hello, thanks for opening an issue!

It's showing all projects under the given parent, which is intended. To filter for the ones you have access to, you can use a flag `--member [YOUR EMAIL]`.
But it makes more sense to have the command do this filter by default, we'll look into changing this behavior.

**Comment by pmanent** [comment]
Thanks!

That's good to know. I tested it and the request went fast and with my projects:

Thanks!
